namespace MakanDownloadManager.Services;

/// <summary>Persian texts: English text (as written in the code and the XAML) -> Persian. "{0}" marks a value inside a sentence.</summary>
public static class LocFa
{
    public static IReadOnlyList<(string English, string Persian)> Entries => Data;

    static readonly List<(string, string)> Data = new()
    {
        ("Add {0} downloads", "افزودن {0} دانلود"),
        ("{0} links", "{0} لینک"),
        ("File names are taken from the servers. Nothing starts until you choose.", "نام فایل‌ها از سرورها گرفته می‌شود. تا وقتی شما انتخاب نکنید چیزی شروع نمی‌شود."),
        ("MP4 video", "ویدیوی MP4"),
        ("TS video (plays in VLC and most players; can be converted to MP4)", "ویدیوی TS (در VLC و بیشتر پخش‌کننده‌ها پخش می‌شود؛ قابل تبدیل به MP4 است)"),
        ("   ·   has a separate audio track", "   ·   دارای صدای جداگانه"),
        ("OK", "تأیید"),
        ("Cancel", "انصراف"),
        ("Close", "بستن"),
        ("Cut", "برش"),
        ("Paste", "جای‌گذاری"),
        ("Select all", "انتخاب همه"),
        ("Apply", "اعمال"),
        ("Default", "پیش‌فرض"),
        ("Browse…", "انتخاب…"),
        ("New…", "جدید…"),
        ("Delete", "حذف"),
        ("Open", "باز کردن"),
        ("Open folder", "باز کردن پوشه"),
        ("Resume selected downloads", "ادامهٔ دانلودهای انتخاب‌شده"),
        ("Stop selected downloads", "توقف دانلودهای انتخاب‌شده"),
        ("Limit total download speed", "محدود کردن سرعت کل دانلود"),
        ("Delete selected downloads (Del)", "حذف دانلودهای انتخاب‌شده (Del)"),
        ("More options & tools", "گزینه‌ها و ابزارهای بیشتر"),
        ("Options & Settings", "گزینه‌ها و تنظیمات"),
        ("Remove finished downloads from the list", "حذف دانلودهای تمام‌شده از فهرست"),
        ("Server learning & health checks", "یادگیری سرور و بررسی سلامت"),
        ("Grab web page links", "استخراج لینک‌های صفحهٔ وب"),
        ("Ignore schedule for this torrent", "نادیده گرفتن زمان‌بندی برای این تورنت"),
        ("Downloads sorted", "دانلودها مرتب شدند"),
        ("_Sort downloads", "_مرتب‌سازی دانلودها"),
        ("Newest first", "جدیدترین ابتدا"),
        ("Oldest first", "قدیمی‌ترین ابتدا"),
        ("Name (A–Z)", "نام (A–Z)"),
        ("Name (Z–A)", "نام (Z–A)"),
        ("Size (largest first)", "حجم (بزرگ‌ترین ابتدا)"),
        ("Size (smallest first)", "حجم (کوچک‌ترین ابتدا)"),
        ("Progress", "پیشرفت"),
        ("Speed", "سرعت"),
        ("Makan", "ماکان"),
        ("Epsilon Download Manager", "اپسیلون دانلود منیجر"),
        ("Options", "تنظیمات"),
        ("Settings", "تنظیمات"),
        ("Status", "وضعیت"),
        ("Size", "حجم"),
        ("Add", "افزودن"),
        ("Download", "دانلود"),
        ("Language", "زبان"),
        ("Type", "نوع"),
        ("Error", "خطا"),
        ("Exit", "خروج"),
        ("About", "درباره"),
        ("Export", "خروجی"),
        ("Import", "ورودی"),
        ("Scheduler", "زمان‌بندی"),
        ("Duplicate link", "لینک تکراری"),
        ("Site grabber", "استخراج‌گر سایت"),
        ("Add Batch Download", "افزودن دانلود دسته‌ای"),
        ("Type an address with a * where the numbers or letters change, for example  https://site.example/photos/img*.jpg", "نشانی را با یک * در جایی که عدد یا حرف تغییر می‌کند بنویسید، مثلاً  https://site.example/photos/img*.jpg"),
        ("Replace the * with", "جایگزینی * با"),
        ("Numbers", "اعداد"),
        ("from", "از"),
        ("to", "تا"),
        ("step", "گام"),
        ("Fill with zeros (001, 002…)", "پر کردن با صفر (001، 002…)"),
        ("Letters", "حروف"),
        ("{0} addresses, from\n{1}\nto\n{2}", "{0} نشانی، از\n{1}\nتا\n{2}"),
        ("The address must start with http:// or https://", "نشانی باید با http:// یا https:// شروع شود"),
        ("Download File Info", "اطلاعات فایل دانلود"),
        ("Address", "نشانی"),
        ("Save as", "ذخیره با نام"),
        ("Save to folder", "ذخیره در پوشه"),
        ("Download later in", "دانلود بعداً در"),
        ("Where 'Download Later' parks it. Start the queue by hand or with the Scheduler.", "«دانلود بعداً» فایل را اینجا نگه می‌دارد. صف را دستی یا با زمان‌بندی شروع کنید."),
        ("Start Download", "شروع دانلود"),
        ("Download Later", "دانلود بعداً"),
        ("Add to queue", "افزودن به صف"),
        ("Enter a file name.", "نام فایل را وارد کنید."),
        ("Choose a folder.", "یک پوشه انتخاب کنید."),
        ("Choose where to save", "محل ذخیره را انتخاب کنید"),
        ("Checking the link…", "در حال بررسی لینک…"),
        ("Size: {0}", "حجم: {0}"),
        ("Size: unknown", "حجم: نامشخص"),
        ("Type: {0}", "نوع: {0}"),
        ("Makan drop target", "هدف رهاسازی ماکان"),
        ("Drop links here to download them. Double-click to open Makan.", "لینک‌ها را اینجا رها کنید تا دانلود شوند. برای باز کردن ماکان دوبار کلیک کنید."),
        ("Open Makan", "باز کردن ماکان"),
        ("Hide the drop target", "پنهان کردن هدف رهاسازی"),
        ("Download complete", "دانلود کامل شد"),
        ("Download Progress", "پیشرفت دانلود"),
        ("DISK LOAD", "بارگذاری از دیسک"),
        ("Loaded {0} from disk", "{0} از دیسک بارگذاری شد"),
        ("No saved data loaded from disk", "دادهٔ ذخیره‌شده‌ای از دیسک بارگذاری نشد"),
        ("CONNECTIONS", "اتصال‌ها"),
        ("SHA-256 ✓ on finish", "SHA-256 ✓ پس از پایان"),
        ("Live illustration of Epsilon's download progress window — every segment is its own connection.", "نمایش زندهٔ پنجرهٔ پیشرفت دانلود اپسیلون — هر بخش اتصال جداگانهٔ خود را دارد."),
        ("Download History", "تاریخچهٔ دانلود"),
        ("Clear history", "پاک کردن تاریخچه"),
        ("Clear the complete download history?\n\nDownloaded files and the current download list are not deleted.", "کل تاریخچهٔ دانلود پاک شود؟\n\nفایل‌های دانلودشده و فهرست دانلود فعلی حذف نمی‌شوند."),
        ("Completed, failed and cancelled transfers", "انتقال‌های تکمیل‌شده، ناموفق و لغوشده"),
        ("File", "فایل"),
        ("URL", "نشانی"),
        ("Started", "شروع"),
        ("Finished", "تمام‌شده"),
        ("Add Download", "افزودن دانلود"),
        ("Link (URL)", "لینک (URL)"),
        ("HTTP or HTTPS link. The file name is taken from the server.", "لینک HTTP یا HTTPS. نام فایل از سرور گرفته می‌شود."),
        ("Leave empty to use your default download folder", "برای استفاده از پوشهٔ پیش‌فرض دانلود خالی بگذارید"),
        ("Connections", "اتصال‌ها"),
        ("(more connections = faster on most servers)", "(اتصال بیشتر = سرعت بیشتر در بیشتر سرورها)"),
        ("Speed limit (KB/s)", "محدودیت سرعت (KB/s)"),
        ("0 = unlimited", "0 = نامحدود"),
        ("Cookie (optional)", "کوکی (اختیاری)"),
        ("Cookie header for sites that need you to be logged in", "سرآیند کوکی برای سایت‌هایی که ورود می‌خواهند"),
        ("Referrer (optional)", "ارجاع‌دهنده (اختیاری)"),
        ("Page the download link came from", "صفحه‌ای که لینک دانلود از آن آمده"),
        ("Enter a valid HTTP/HTTPS link.", "یک لینک معتبر HTTP/HTTPS وارد کنید."),
        ("Choose where to save this download", "محل ذخیرهٔ این دانلود را انتخاب کنید"),
        ("Download All Links with Makan", "دانلود همهٔ لینک‌ها با ماکان"),
        ("Download All Links – {0}", "دانلود همهٔ لینک‌ها – {0}"),
        ("Tick the links you want, then choose Start Download or Download Later. You may wait while Makan checks the sizes and file types.", "لینک‌های دلخواه را تیک بزنید، سپس «شروع دانلود» یا «دانلود بعداً» را بزنید. ممکن است کمی صبر کنید تا ماکان حجم و نوع فایل‌ها را بررسی کند."),
        ("File Name", "نام فایل"),
        ("File Type", "نوع فایل"),
        ("Download from", "دانلود از"),
        ("Save to", "ذخیره در"),
        ("Link Text", "متن لینک"),
        ("Every file to the folder for its category (Video, Music, Programs…)", "هر فایل در پوشهٔ دستهٔ خودش (ویدیو، موسیقی، برنامه‌ها…)"),
        ("All files to one category:", "همهٔ فایل‌ها در یک دسته:"),
        ("All files to one folder:", "همهٔ فایل‌ها در یک پوشه:"),
        ("Check All", "انتخاب همه"),
        ("Uncheck All", "لغو انتخاب همه"),
        ("Hide web pages (HTML)", "پنهان کردن صفحه‌های وب (HTML)"),
        ("Hide images of this page", "پنهان کردن تصاویر این صفحه"),
        ("Download Later goes to:", "دانلود بعداً به این صف می‌رود:"),
        ("Tick at least one link.", "دست‌کم یک لینک را تیک بزنید."),
        ("Choose where to save all files", "محل ذخیرهٔ همهٔ فایل‌ها را انتخاب کنید"),
        ("{0} of {1} shown links ticked", "{0} از {1} لینک نمایش‌داده‌شده تیک خورده"),
        ("_Tasks", "وظایف"),
        ("Add _new download…", "افزودن دانلود جدید…"),
        ("Add _torrent or magnet link…", "افزودن تورنت یا لینک مگنت…"),
        ("Add Torrent", "افزودن تورنت"),
        ("Add a magnet link or a .torrent file", "افزودن یک لینک مگنت یا فایل تورنت"),
        ("Add torrent", "افزودن تورنت"),
        ("Paste a magnet link:", "یک لینک مگنت جای‌گذاری کنید:"),
        ("or", "یا"),
        ("Browse for a .torrent file…", "انتخاب یک فایل تورنت…"),
        ("Torrent files", "فایل‌های تورنت"),
        ("All files", "همهٔ فایل‌ها"),
        ("That doesn't look like a magnet link or a .torrent file.", "این یک لینک مگنت یا فایل تورنت معتبر به نظر نمی‌رسد."),
        ("Already in the list", "از قبل در فهرست است"),
        ("Add _batch download…", "افزودن دانلود دسته‌ای…"),
        ("Add batch download from _clipboard", "افزودن دانلود دسته‌ای از کلیپ‌بورد"),
        ("Run site _grabber…", "اجرای استخراج‌گر سایت…"),
        ("Show _drop target", "نمایش هدف رهاسازی"),
        ("_Export", "خروجی گرفتن"),
        ("To _text file…", "به فایل متنی…"),
        ("_Import", "وارد کردن"),
        ("From _text file…", "از فایل متنی…"),
        ("E_xit", "خروج"),
        ("_File", "فایل"),
        ("_Open", "باز کردن"),
        ("Open _folder", "باز کردن پوشه"),
        ("_Copy address", "کپی نشانی"),
        ("Export _diagnostic report", "خروجی گزارش عیب‌یابی"),
        ("_Downloads", "دانلودها"),
        ("_Resume", "ادامه"),
        ("_Stop", "توقف"),
        ("Stop _all", "توقف همه"),
        ("_Scheduler…", "زمان‌بندی…"),
        ("Start the _main download queue", "شروع صف اصلی دانلود"),
        ("Stop all _queues", "توقف همهٔ صف‌ها"),
        ("Resume all stopped downloads", "ادامهٔ همهٔ دانلودهای متوقف‌شده"),
        ("Re_download", "دانلود دوباره"),
        ("_Delete", "حذف"),
        ("Delete _completed", "حذف تکمیل‌شده‌ها"),
        ("Raise priority", "افزایش اولویت"),
        ("Lower priority", "کاهش اولویت"),
        ("_Options…", "تنظیمات…"),
        ("_View", "نما"),
        ("_Categories panel", "پنل دسته‌بندی‌ها"),
        ("Download _history…", "تاریخچهٔ دانلود…"),
        ("_Help", "راهنما"),
        ("_About Epsilon Download Manager", "دربارهٔ اپسیلون دانلود منیجر"),
        ("Search the list", "جستجو در فهرست"),
        ("Add a download (Ctrl+N)", "افزودن دانلود (Ctrl+N)"),
        ("Add URL", "افزودن لینک"),
        ("Resume the selected downloads", "ادامهٔ دانلودهای انتخاب‌شده"),
        ("Resume", "ادامه"),
        ("Stop the selected downloads", "توقف دانلودهای انتخاب‌شده"),
        ("Stop", "توقف"),
        ("Stop every running download", "توقف همهٔ دانلودهای در حال اجرا"),
        ("Stop All", "توقف همه"),
        ("Start All", "شروع همه"),
        ("Open download schedules and queues", "باز کردن زمان‌بندی‌ها و صف‌های دانلود"),
        ("Delete the selected downloads (Del)", "حذف دانلودهای انتخاب‌شده (Del)"),
        ("Remove all finished downloads from the list", "حذف همهٔ دانلودهای تمام‌شده از فهرست"),
        ("Delete Completed", "حذف تکمیل‌شده‌ها"),
        ("Start a queue (you choose which)", "شروع یک صف (خودتان انتخاب می‌کنید)"),
        ("Start Queue", "شروع صف"),
        ("Stop a running queue", "توقف یک صف در حال اجرا"),
        ("Stop Queue", "توقف صف"),
        ("Queues, start/stop times, shut down when done", "صف‌ها، زمان شروع/توقف، خاموش شدن پس از پایان"),
        ("Grab the links of a web page", "گرفتن لینک‌های یک صفحهٔ وب"),
        ("Grabber", "استخراج‌گر"),
        ("Ready", "آماده"),
        ("LIBRARY", "کتابخانه"),
        ("Redownload", "دانلود دوباره"),
        ("Copy address", "کپی نشانی"),
        ("Time left", "زمان باقی‌مانده"),
        ("Transfer rate", "سرعت انتقال"),
        ("Last Try Date", "تاریخ آخرین تلاش"),
        ("Description", "توضیحات"),
        ("{0} active · {1} in list", "{0} فعال · {1} در فهرست"),
        ("0 active", "0 فعال"),
        ("All Downloads", "همهٔ دانلودها"),
        ("Unfinished", "ناتمام"),
        ("Queues", "صف‌ها"),
        ("Queue", "صف"),
        ("About Epsilon Download Manager", "دربارهٔ Epsilon Download Manager"),
        ("Version", "نسخه"),
        ("Created by", "ساخته‌شده توسط"),
        ("Project", "پروژه"),
        ("Proxy / Socks", "پراکسی / ساکس"),
        ("No proxy", "بدون پراکسی"),
        ("Use system settings", "استفاده از تنظیمات سیستم"),
        ("Manual proxy configuration", "پیکربندی دستی پراکسی"),
        ("Proxy server address", "آدرس سرور پراکسی"),
        ("Port", "پورت"),
        ("Username (optional)", "نام کاربری (اختیاری)"),
        ("Password", "رمز عبور"),
        ("Use this proxy for:", "استفاده از این پراکسی برای:"),
        ("http", "http"),
        ("https", "https"),
        ("Route regular downloads through a proxy server (like IDM's Proxy/Socks tab). This applies to ordinary HTTP/HTTPS downloads only - not torrents or YouTube-style downloads, which have their own separate connections.", "دانلودهای معمولی را از طریق یک سرور پراکسی مسیر کنید (مثل تب Proxy/Socks در IDM). این فقط روی دانلودهای معمولی HTTP/HTTPS اثر می‌گذارد - نه تورنت‌ها یا دانلودهای سبک یوتیوب که اتصال‌های جداگانهٔ خودشان را دارند."),
        ("The password is stored encrypted, the same way everything else sensitive in Epsilon Download Manager is. A SOCKS proxy is not supported yet, only a regular HTTP proxy (most proxy servers, including SOCKS-capable ones, also accept plain HTTP proxy connections on a different port - check your provider).", "رمز عبور به‌صورت رمزنگاری‌شده ذخیره می‌شود، درست مثل هر چیز حساس دیگری در Epsilon Download Manager. پراکسی SOCKS هنوز پشتیبانی نمی‌شود، فقط پراکسی معمولی HTTP (بیشتر سرورهای پراکسی، از جمله آن‌هایی که SOCKS هم دارند، اتصال HTTP ساده را هم روی پورت دیگری می‌پذیرند - از ارائه‌دهندهٔ خود بپرسید)."),
        ("Website", "وب‌سایت"),
        ("Email", "ایمیل"),
        ("Fast, intelligent, private — built for Windows", "سریع، هوشمند، خصوصی — ساخته‌شده برای ویندوز"),
        ("Getting started", "شروع کار"),
        ("_Getting started", "_شروع کار"),
        ("Welcome to Epsilon Download Manager", "به Epsilon Download Manager خوش آمدید"),
        ("A couple of things finish setting it up:", "چند مورد کوچک باقی مانده تا راه‌اندازی کامل شود:"),
        ("Browser extension", "افزونهٔ مرورگر"),
        ("Show me how", "راهنمایی کن"),
        ("Connected - Makan will offer to grab video/audio and captured downloads.", "متصل است - ماکان دریافت ویدیو/صدا و دانلودهای گرفته‌شده را پیشنهاد می‌دهد."),
        ("Not yet - open your browser's extensions page and turn it on.", "هنوز نه - صفحهٔ افزونه‌های مرورگرتان را باز کرده و آن را روشن کنید."),
        ("Video downloads (YouTube and similar sites)", "دانلود ویدیو (یوتیوب و سایت‌های مشابه)"),
        ("Ready.", "آماده است."),
        ("Not installed yet - needed only for YouTube-style sites.", "هنوز نصب نشده - فقط برای سایت‌های شبیه یوتیوب لازم است."),
        ("Install now", "اکنون نصب کن"),
        ("Download folder", "پوشهٔ دانلود"),
        ("Change…", "تغییر…"),
        ("Get started", "بزن بریم"),
        ("More", "بیشتر"),
        ("More: stop all, delete completed, queues, scheduler, intelligent center, grabber, theme", "بیشتر: توقف همه، حذف تمام‌شده‌ها، صف‌ها، زمان‌بندی، مرکز هوشمند، گیرندهٔ لینک، پوسته"),
        ("Play (downloaded part)", "پخش (بخش دانلودشده)"),
        ("Not enough of this file has downloaded yet to play it.", "هنوز به اندازهٔ کافی از این فایل دانلود نشده تا قابل پخش باشد."),
        ("Remote", "دسترسی از راه دور"),
        ("View your downloads and add new ones from a phone's browser, on the same Wi-Fi/network - without a separate app.", "دانلودهای خود را از مرورگر گوشی، در همان شبکهٔ وای‌فای، ببینید و مورد جدید اضافه کنید - بدون نیاز به اپ جداگانه."),
        ("Plain, unencrypted HTTP, meant for a home network only - never forward this port through a router to the internet. Anyone with the address below can see and add downloads, so only share it with people you trust on your own network.", "این فقط HTTP ساده و رمزنگاری‌نشده و برای شبکهٔ خانگی است - هرگز این پورت را از طریق روتر به اینترنت باز نکنید. هرکس آدرس زیر را داشته باشد می‌تواند دانلودها را ببیند و مورد اضافه کند، پس فقط با افراد مورد اعتماد در همان شبکه به اشتراک بگذارید."),
        ("Turn on the remote status page", "صفحهٔ وضعیت از راه دور را روشن کن"),
        ("Port:", "پورت:"),
        ("Open this on your phone's browser:", "این را در مرورگر گوشی باز کنید:"),
        ("Copy", "کپی"),
        ("Get a new address (invalidates the old one)", "یک آدرس جدید بگیر (آدرس قبلی از کار می‌افتد)"),
        ("Bring Makan's window to the front when a new download arrives (from the browser, a magnet link, etc.)", "با رسیدن دانلود جدید (از مرورگر، لینک مگنت و غیره) پنجرهٔ Makan به جلو بیاید"),
        ("Speed boost", "افزایش سرعت"),
        ("Pause Windows Update and similar background traffic while a download is running", "هنگام دانلود، آپدیت ویندوز و ترافیک پس‌زمینهٔ مشابه متوقف شود"),
        ("Off by default. Needs administrator rights, which Makan does not request on its own - without them this does nothing and says so, rather than failing silently. It only pauses a short list of Windows services (Windows Update, BITS, Delivery Optimization); it cannot stop other programs that are already mid-transfer, and everything paused resumes as soon as nothing is downloading, or Makan closes.", "به‌طور پیش‌فرض خاموش است. نیاز به دسترسی مدیر سیستم دارد که Makan خودش درخواست نمی‌کند - بدون آن، این گزینه کاری نمی‌کند و همین را هم اعلام می‌کند، نه اینکه بی‌سروصدا شکست بخورد. فقط چند سرویس محدود ویندوز (Windows Update، BITS، Delivery Optimization) را متوقف می‌کند؛ نمی‌تواند برنامه‌های دیگری را که همین حالا در حال انتقال داده هستند متوقف کند، و به محض تمام شدن دانلودها یا بسته شدن Makan همه چیز دوباره از سر گرفته می‌شود."),
        ("Playlist found", "پلی‌لیست پیدا شد"),
        ("This looks like a playlist:", "به نظر می‌رسد این یک پلی‌لیست است:"),
        ("{0} videos", "{0} ویدیو"),
        ("Quality for every video:", "کیفیت برای همهٔ ویدیوها:"),
        ("Download all {0} videos", "دانلود هر {0} ویدیو"),
        ("Just this one video", "فقط همین یک ویدیو"),
        ("Added {0} video(s) from the playlist", "{0} ویدیو از پلی‌لیست اضافه شد"),
        ("({0} already in the list)", "({0} از قبل در فهرست بود)"),
        ("Compressed", "فشرده"),
        ("Documents", "اسناد"),
        ("Music", "موسیقی"),
        ("Programs", "برنامه‌ها"),
        ("Video", "ویدیو"),
        ("General", "عمومی"),
        ("Downloading", "در حال دانلود"),
        ("Complete", "کامل"),
        ("Stopped", "متوقف"),
        ("Stopped {0}", "متوقف {0}"),
        ("Queued {0}", "در صف {0}"),
        ("Queued", "در صف"),
        ("Cancelled", "لغو شده"),
        ("Download failed", "دانلود ناموفق بود"),
        ("Recovered after application restart.", "پس از راه‌اندازی مجدد برنامه بازیابی شد."),
        ("Retrying: {0}", "تلاش مجدد: {0}"),
        ("Saved without conversion", "بدون تبدیل ذخیره شد"),
        ("Add clipboard URL", "افزودن لینک کلیپ‌بورد"),
        ("Still running in the tray. Right-click the icon to exit.", "ماکان در سینی سیستم در حال اجراست. برای خروج روی آیکون راست‌کلیک کنید."),
        ("The antivirus program reported a problem with {0}", "برنامهٔ آنتی‌ویروس دربارهٔ {0} مشکلی گزارش کرد"),
        ("That link is already in the list", "این لینک از قبل در فهرست است"),
        ("Already in the list: {0}", "از قبل در فهرست است: {0}"),
        ("This link is already in the list ({0}).\n\nYes = download it again under a new name\nNo = download it again and replace the existing file\nCancel = do nothing", "این لینک از قبل در فهرست است ({0}).\n\nبله = دانلود دوباره با نام جدید\nخیر = دانلود دوباره و جایگزینی فایل موجود\nانصراف = هیچ کاری نکن"),
        ("Can't use the folder \"{0}\":\n{1}", "استفاده از پوشهٔ «{0}» ممکن نیست:\n{1}"),
        ("Download started", "دانلود شروع شد"),
        ("Added to the queue \"{0}\"", "به صف «{0}» افزوده شد"),
        ("Main download queue", "صف اصلی دانلود"),
        ("Couldn't check the link ({0}). You can still download it.", "بررسی لینک ممکن نشد ({0}). هنوز می‌توانید آن را دانلود کنید."),
        ("Added {0} download(s)", "{0} دانلود اضافه شد"),
        ("Added {0} download(s) to the queue", "{0} دانلود به صف اضافه شد"),
        ("Added {0} download(s) ({1} skipped)", "{0} دانلود اضافه شد ({1} ردشده)"),
        ("Added {0} download(s) to the queue ({1} skipped)", "{0} دانلود به صف اضافه شد ({1} ردشده)"),
        ("Video download started", "دانلود ویدیو شروع شد"),
        ("Video added to the queue", "ویدیو به صف افزوده شد"),
        ("The clipboard doesn't contain an HTTP/HTTPS link.", "کلیپ‌بورد لینک HTTP/HTTPS ندارد."),
        ("No download link found in what you dropped.", "در چیزی که رها کردید لینک دانلودی پیدا نشد."),
        ("There are no addresses to show.", "نشانی‌ای برای نمایش وجود ندارد."),
        ("Run site grabber", "اجرای استخراج‌گر سایت"),
        ("Address of the web page whose links and files you want to grab:", "نشانی صفحهٔ وبی که می‌خواهید لینک‌ها و فایل‌هایش را بگیرید:"),
        ("Reading the page…", "در حال خواندن صفحه…"),
        ("Found {0} addresses", "{0} نشانی پیدا شد"),
        ("The list is empty.", "فهرست خالی است."),
        ("Exported {0} address(es) to {1}", "{0} نشانی در {1} ذخیره شد"),
        ("No http:// or https:// addresses were found in that file.", "در آن فایل هیچ نشانی http:// یا https:// پیدا نشد."),
        ("Export addresses to a text file", "ذخیرهٔ نشانی‌ها در یک فایل متنی"),
        ("Import addresses from a text file", "خواندن نشانی‌ها از یک فایل متنی"),
        ("Priority changed", "اولویت تغییر کرد"),
        ("Also delete the downloaded file(s) from disk?\n\nYes = delete file and remove from list\nNo = remove from list only", "فایل(های) دانلودشده از دیسک هم حذف شوند؟\n\nبله = حذف فایل و برداشتن از فهرست\nخیر = فقط برداشتن از فهرست"),
        ("Epsilon Download Manager {0}\n\nMulti-connection downloads, video grabbing (HLS / DASH), browser integration.\nNothing starts until you ask.", "اپسیلون دانلود منیجر {0}\n\nدانلود چندارتباطی، دریافت ویدیو (HLS / DASH)، یکپارچگی با مرورگر.\nهیچ چیز تا وقتی نخواهید شروع نمی‌شود."),
        ("Diagnostic report: {0}", "گزارش عیب‌یابی: {0}"),
        ("{0}  ({1} files)", "{0}  ({1} فایل)"),
        ("Every queue is already running", "همهٔ صف‌ها در حال اجرا هستند"),
        ("No queue is running", "هیچ صفی در حال اجرا نیست"),
        ("Scheduler…", "زمان‌بندی…"),
        ("Remove from queue", "حذف از صف"),
        ("Media / Site Grabber", "رسانه / استخراج‌گر سایت"),
        ("Media & Site Grabber", "رسانه و استخراج‌گر سایت"),
        ("HLS (.m3u8), DASH (.mpd), stream inspection and FFmpeg extraction", "HLS (.m3u8)، DASH (.mpd)، بررسی جریان و استخراج با FFmpeg"),
        ("Stream or webpage URL", "نشانی جریان یا صفحهٔ وب"),
        ("Path to ffmpeg.exe", "مسیر ffmpeg.exe"),
        ("Inspect manifest", "بررسی مانیفست"),
        ("Grab page assets", "گرفتن منابع صفحه"),
        ("Download selected", "دانلود انتخاب‌شده"),
        ("Download source", "دانلود منبع"),
        ("Quality", "کیفیت"),
        ("Codec", "کدک"),
        ("Bitrate", "نرخ بیت"),
        ("Makan Site Grabber", "استخراج‌گر سایت ماکان"),
        ("Reading manifest…", "در حال خواندن مانیفست…"),
        ("Found {0} stream variant(s). Select one to download.", "{0} گونهٔ جریان پیدا شد. یکی را برای دانلود انتخاب کنید."),
        ("Found {0} HTTP/HTTPS assets.", "{0} منبع HTTP/HTTPS پیدا شد."),
        ("A stream is already being saved. Please wait for it to finish.", "یک جریان در حال ذخیره است. لطفاً تا پایان آن صبر کنید."),
        ("FFmpeg is saving the stream… (closing this window cancels it)", "FFmpeg در حال ذخیرهٔ جریان است… (بستن این پنجره آن را لغو می‌کند)"),
        ("Complete: {0}", "کامل شد: {0}"),
        ("Cancelled.", "لغو شد."),
        ("Do it now", "همین حالا"),
        ("New queue", "صف جدید"),
        ("Queue name (the main queue keeps its name)", "نام صف (صف اصلی نام خود را نگه می‌دارد)"),
        ("Schedule", "برنامه"),
        ("Start download when Makan starts", "شروع دانلود هنگام اجرای ماکان"),
        ("Start download at", "شروع دانلود در ساعت"),
        ("24-hour time, for example 23:30", "ساعت ۲۴ساعته، مثلاً 23:30"),
        ("(24-hour, e.g. 23:30)", "(۲۴ ساعته، مثلاً 23:30)"),
        ("Once on", "یک بار در تاریخ"),
        ("Daily, on:", "روزانه، در روزهای:"),
        ("Sunday", "یکشنبه"),
        ("Monday", "دوشنبه"),
        ("Tuesday", "سه‌شنبه"),
        ("Wednesday", "چهارشنبه"),
        ("Thursday", "پنجشنبه"),
        ("Friday", "جمعه"),
        ("Saturday", "شنبه"),
        ("Stop download at", "توقف دانلود در ساعت"),
        ("24-hour time, for example 07:30", "ساعت ۲۴ساعته، مثلاً 07:30"),
        ("Number of retries for each file if downloading failed:", "تعداد تلاش مجدد برای هر فایل در صورت شکست دانلود:"),
        ("When every download in the queue is finished:", "وقتی همهٔ دانلودهای صف تمام شد:"),
        ("Open the following file:", "این فایل را باز کن:"),
        ("Exit Makan", "خروج از ماکان"),
        ("Turn off the computer:", "خاموش کردن رایانه:"),
        ("Shut down", "خاموش کردن"),
        ("Hibernate", "خواب زمستانی"),
        ("Sleep", "خواب"),
        ("Restart", "راه‌اندازی مجدد"),
        ("Force programs to close (unsaved work is lost)", "بستن اجباری برنامه‌ها (کارهای ذخیره‌نشده از بین می‌روند)"),
        ("A 60-second warning with a Cancel button is always shown before the computer is turned off.", "پیش از خاموش شدن رایانه همیشه یک هشدار ۶۰ ثانیه‌ای با دکمهٔ انصراف نشان داده می‌شود."),
        ("Files in the queue", "فایل‌های صف"),
        ("1 to 16", "1 تا 16"),
        ("files at the same time", "فایل به‌طور همزمان"),
        ("Move down", "انتقال به پایین"),
        ("Move up", "انتقال به بالا"),
        ("Start now", "شروع همین حالا"),
        ("Start time must look like 23:30 (24-hour).", "زمان شروع باید مثل 23:30 (۲۴ ساعته) باشد."),
        ("Stop time must look like 07:30 (24-hour).", "زمان توقف باید مثل 07:30 (۲۴ ساعته) باشد."),
        ("The number of retries must be between 0 and 100.", "تعداد تلاش مجدد باید بین 0 و 100 باشد."),
        ("The number of files at the same time must be between 1 and 16.", "تعداد فایل‌های همزمان باید بین 1 و 16 باشد."),
        ("Tick at least one day.", "دست‌کم یک روز را تیک بزنید."),
        ("Choose the date.", "تاریخ را انتخاب کنید."),
        ("Running", "در حال اجرا"),
        ("Not running", "اجرا نمی‌شود"),
        ("File to open when the queue is finished", "فایلی که پس از پایان صف باز شود"),
        ("Delete the queue \"{0}\"?\nIts downloads stay in the list (stopped).", "صف «{0}» حذف شود؟\nدانلودهای آن (متوقف‌شده) در فهرست می‌مانند."),
        ("All downloads in the queue are finished. The computer will {0} in:", "همهٔ دانلودهای صف تمام شد. {0} در:"),
        ("shut down", "رایانه خاموش می‌شود"),
        ("hibernate", "رایانه به خواب زمستانی می‌رود"),
        ("go to sleep", "رایانه به حالت خواب می‌رود"),
        ("restart", "رایانه دوباره راه‌اندازی می‌شود"),
        ("Browser integration", "یکپارچگی با مرورگر"),
        ("Set up / repair…", "راه‌اندازی / تعمیر…"),
        ("Check again", "بررسی دوباره"),
        ("Start Makan (in the tray) when Windows starts", "اجرای ماکان (در سینی سیستم) هنگام شروع ویندوز"),
        ("Offer to download links that I copy to the clipboard", "پیشنهاد دانلود لینک‌هایی که در کلیپ‌بورد کپی می‌کنم"),
        ("Take over downloads from these browsers", "در اختیار گرفتن دانلود از این مرورگرها"),
        ("Google Chrome, Brave and other Chromium browsers", "گوگل کروم، Brave و دیگر مرورگرهای کرومیوم"),
        ("Microsoft Edge", "مایکروسافت اج"),
        ("Mozilla Firefox", "موزیلا فایرفاکس"),
        ("Opera", "اپرا"),
        ("Vivaldi", "ویوالدی"),
        ("Other browsers", "مرورگرهای دیگر"),
        ("Hold Alt while clicking a download link to let the browser download it instead of Makan.", "هنگام کلیک روی لینک دانلود کلید Alt را نگه دارید تا مرورگر (نه ماکان) آن را دانلود کند."),
        ("The language changes when Makan is restarted.", "زبان پس از اجرای دوبارهٔ ماکان عوض می‌شود."),
        ("File types", "نوع فایل‌ها"),
        ("Take over downloads of these file types (separate with spaces; R0* matches .r00, .r01 …). Leave empty to take over every type.", "دانلود این نوع فایل‌ها را در اختیار بگیر (با فاصله جدا کنید؛ R0* یعنی .r00 و .r01 و …). برای همهٔ انواع خالی بگذارید."),
        ("Leave downloads from these sites to the browser (separate with spaces, * means anything)", "دانلود از این سایت‌ها را به مرورگر واگذار کن (با فاصله جدا کنید، * یعنی هر چیزی)"),
        ("Leave downloads from these addresses to the browser (one per line, * means anything)", "دانلود از این نشانی‌ها را به مرورگر واگذار کن (در هر خط یکی، * یعنی هر چیزی)"),
        ("Category", "دسته"),
        ("File types in this category (separate with spaces)", "نوع فایل‌های این دسته (با فاصله جدا کنید)"),
        ("Folder for this category", "پوشه برای این دسته"),
        ("Change the folder of a category to the one I chose last", "پوشهٔ هر دسته را به آخرین پوشه‌ای که انتخاب کردم تغییر بده"),
        ("Main download folder (used for 'General' and as the base of the other categories)", "پوشهٔ اصلی دانلود (برای «عمومی» و پایهٔ دسته‌های دیگر)"),
        ("Give finished files the date reported by the server", "به فایل‌های تمام‌شده تاریخ گزارش‌شده توسط سرور را بده"),
        ("Temporary folder (parts of unfinished downloads)", "پوشهٔ موقت (بخش‌های دانلودهای ناتمام)"),
        ("Empty = next to the final file. A folder on another physical drive makes assembling big files faster. Applies to new downloads.", "خالی = کنار فایل نهایی. پوشه‌ای روی درایو فیزیکی دیگر ادغام فایل‌های بزرگ را سریع‌تر می‌کند. برای دانلودهای جدید اعمال می‌شود."),
        ("Downloads", "دانلودها"),
        ("Show the 'Download File Info' window before a download starts", "پیش از شروع دانلود پنجرهٔ «اطلاعات فایل دانلود» را نشان بده"),
        ("Do not start downloading, only add files to the queue", "دانلود را شروع نکن، فقط فایل‌ها را به صف اضافه کن"),
        ("Show a 'download complete' window", "پنجرهٔ «دانلود کامل شد» را نشان بده"),
        ("The 'download complete' window is not shown for files started by a queue.", "پنجرهٔ «دانلود کامل شد» برای فایل‌هایی که صف شروع کرده نشان داده نمی‌شود."),
        ("Show the queue chooser when I press Download Later", "با زدن «دانلود بعداً» انتخاب صف را نشان بده"),
        ("Show the queue chooser in the Download All Links window", "انتخاب صف را در پنجرهٔ دانلود همهٔ لینک‌ها نشان بده"),
        ("Ignore file modification time changes when resuming a download", "هنگام ادامهٔ دانلود تغییر زمان ویرایش فایل را نادیده بگیر"),
        ("If a download link is added twice:", "اگر یک لینک دانلود دو بار اضافه شود:"),
        ("Show a window and ask what to do", "پنجره‌ای نشان بده و بپرس چه کنم"),
        ("Add it again with a numeric suffix", "دوباره با پسوند عددی اضافه کن"),
        ("Overwrite the existing file", "فایل موجود را بازنویسی کن"),
        ("Skip it (keep the existing download)", "رد کن (دانلود موجود بماند)"),
        ("User-Agent for downloads I add by hand", "User-Agent برای دانلودهایی که خودم اضافه می‌کنم"),
        ("Scan finished downloads with an antivirus program", "دانلودهای تمام‌شده را با برنامهٔ آنتی‌ویروس بررسی کن"),
        ("Program", "برنامه"),
        ("Arguments (%1 stands for the downloaded file)", "آرگومان‌ها (%1 یعنی فایل دانلودشده)"),
        ("Connection", "اتصال"),
        ("Maximum simultaneous downloads (files that are not started by a queue)", "بیشترین دانلود همزمان (فایل‌هایی که صف شروع نکرده)"),
        ("Global speed limit (KB/s, 0 = unlimited)", "محدودیت سرعت کلی (KB/s، 0 = نامحدود)"),
        ("Default connections per download", "اتصال‌های پیش‌فرض برای هر دانلود"),
        ("Resume unfinished downloads by themselves when Makan starts", "هنگام اجرای ماکان دانلودهای ناتمام خودکار ادامه یابند"),
        ("FFmpeg (optional)", "FFmpeg (اختیاری)"),
        ("Videos are always saved as .ts without it. FFmpeg is only needed to convert them to .mp4 or to merge a separate audio track. Leave empty to search PATH / the Makan folder.", "بدون آن ویدیوها همیشه با پسوند .ts ذخیره می‌شوند. FFmpeg فقط برای تبدیل به .mp4 یا ادغام صدای جدا لازم است. برای جستجو در PATH / پوشهٔ ماکان خالی بگذارید."),
        ("connected", "متصل"),
        ("not set up", "راه‌اندازی نشده"),
        ("The installer script (install-browser-integration.ps1) was not found next to Makan. Run it from the publish folder.", "اسکریپت نصب (install-browser-integration.ps1) کنار ماکان پیدا نشد. آن را از پوشهٔ publish اجرا کنید."),
        ("Everything that is not listed in another category", "هر چیزی که در دستهٔ دیگری نیامده"),
        ("A category with that name already exists.", "دسته‌ای با این نام از قبل وجود دارد."),
        ("New category", "دستهٔ جدید"),
        ("Name of the new category:", "نام دستهٔ جدید:"),
        ("Delete the category \"{0}\"? Its files are not touched; new downloads of its types go to General.", "دستهٔ «{0}» حذف شود؟ به فایل‌های آن دست زده نمی‌شود؛ دانلودهای جدیدِ انواع آن به «عمومی» می‌روند."),
        ("Can't use the {0} folder:\n{1}", "استفاده از پوشهٔ {0} ممکن نیست:\n{1}"),
        ("main download", "اصلی دانلود"),
        ("temporary", "موقت"),
        ("category", "دسته"),
        ("Makan must restart to change the language. Restart now?", "برای تغییر زبان باید ماکان دوباره اجرا شود. اکنون دوباره اجرا شود؟"),
        ("Antivirus program", "برنامهٔ آنتی‌ویروس"),
        ("Find ffmpeg.exe", "یافتن ffmpeg.exe"),
        ("Main download folder", "پوشهٔ اصلی دانلود"),
        ("Temporary folder", "پوشهٔ موقت"),
        ("{0} did not work:\n\n{1}\n\nDetails are in the log (Diagnostics report). Please send this message if it keeps happening.", "{0} انجام نشد:\n\n{1}\n\nجزئیات در گزارش ثبت شده است (گزارش عیب‌یابی). اگر تکرار شد این پیام را بفرستید."),
        ("Opening the window", "باز کردن پنجره"),
        ("The download complete window", "پنجرهٔ «دانلود کامل شد»"),
        ("Reading {0}", "خواندن {0}"),
        ("Creating the main window failed", "ساخت پنجرهٔ اصلی ناموفق بود"),
        ("Download video", "دانلود ویدیو"),
        ("Open Options", "باز کردن تنظیمات"),
        ("Try again", "تلاش دوباره"),
        ("Choice", "گزینه"),
        ("Switch between the light and the dark theme", "جابه‌جایی بین پوستهٔ روشن و تاریک"),
        ("Theme", "پوسته"),
        ("Lilac", "یاسی"),
        ("Dracula", "دراکولا"),
        ("Uhnohh", "اوه‌نه"),
        ("Obsidian", "ابسیدین"),
        ("Nebula", "سحابی"),
        ("Makan (blue grey)", "ماکان (آبی خاکستری)"),
        ("Obsidian (black)", "ابسیدین (مشکی)"),
        ("Nebula (dark violet)", "سحابی (بنفش تیره)"),
        ("Lilac (dark lilac)", "یاسی (یاسی تیره)"),
        ("Dracula (dark red)", "دراکولا (قرمز تیره)"),
        ("Uhnohh (dark yellow)", "اوه‌نه (زرد تیره)"),
        ("Download status", "وضعیت دانلود"),
        ("File size", "حجم فایل"),
        ("Downloaded", "دانلود شده"),
        ("Resume capability", "امکان ادامه دادن"),
        ("Speed Limiter", "محدودکنندهٔ سرعت"),
        ("Use Speed Limiter", "استفاده از محدودکنندهٔ سرعت"),
        ("Limit the total download speed (like IDM's Speed Limiter)", "محدود کردن مجموع سرعت دانلود (مانند محدودکنندهٔ سرعت IDM)"),
        ("Caps the combined speed of every download and torrent.", "مجموع سرعت همهٔ دانلودها و تورنت‌ها را محدود می‌کند."),
        ("Limit enabled", "محدودیت فعال است"),
        ("Apply the entered speed", "اعمال سرعت واردشده"),
        ("Across all downloads combined", "بین مجموع همهٔ دانلودها"),
        ("To each download separately", "به‌صورت جداگانه برای هر دانلود"),
        ("Apply this limit", "اعمال این محدودیت"),
        ("Separately to each download", "به‌صورت جداگانه برای هر دانلود"),
        ("Limit download speed", "محدود کردن سرعت دانلود"),
        ("KB/s", "کیلوبایت بر ثانیه"),
        ("Quick presets", "پیش‌تنظیم‌های سریع"),
        ("This also limits how fast torrents download.", "این کار سرعت دانلود تورنت‌ها را نیز محدود می‌کند."),
        ("Download speed limited to {0} — click to change", "سرعت دانلود به {0} محدود شده — برای تغییر کلیک کنید"),

        // ---- BitTorrent options tab
        ("BitTorrent", "بیت‌تورنت"),
        ("Queueing", "صف‌بندی"),
        ("Random port", "پورت تصادفی"),
        ("Port used for incoming connections:", "پورت مورد استفاده برای اتصالات ورودی:"),
        ("Changing the port, DHT or peer exchange needs Makan to restart before it takes effect.", "تغییر پورت، DHT یا تبادل همتا برای اعمال شدن نیاز به راه‌اندازی مجدد Makan دارد."),
        ("Enable DHT (find peers for a magnet link even without a working tracker)", "فعال‌سازی DHT (یافتن همتاها برای لینک مگنت حتی بدون ردیاب فعال)"),
        ("Enable peer exchange (learn about more peers from the ones already connected)", "فعال‌سازی تبادل همتا (یافتن همتاهای بیشتر از طریق همتاهای متصل)"),
        ("Global torrent upload limit (KB/s, 0 = unlimited)", "محدودیت آپلود کلی تورنت‌ها (کیلوبایت بر ثانیه، ۰ = نامحدود)"),
        ("Global torrent download limit (KB/s, 0 = unlimited)", "محدودیت دانلود کلی تورنت‌ها (کیلوبایت بر ثانیه، ۰ = نامحدود)"),
        ("No automatic torrent speed cap is applied. Only limits you enter here or in Torrent details can limit torrent speed.", "هیچ محدودیت سرعت خودکاری برای تورنت اعمال نمی‌شود. فقط محدودیت‌هایی که اینجا یا در جزئیات تورنت وارد می‌کنید می‌توانند سرعت تورنت را محدود کنند."),
        ("Separate from the toolbar's Speed Limiter, which only covers ordinary downloads.", "این جدا از محدودکنندهٔ سرعت نوار ابزار است که فقط دانلودهای عادی را پوشش می‌دهد."),
        ("Caps the speed of ordinary downloads. Torrents have their own limits in Options > BitTorrent.", "سرعت دانلودهای عادی را محدود می‌کند. تورنت‌ها محدودیت‌های جداگانهٔ خود را در تنظیمات > بیت‌تورنت دارند."),
        ("Torrents have their own limits in Options > BitTorrent.", "تورنت‌ها محدودیت‌های جداگانهٔ خود را در تنظیمات > بیت‌تورنت دارند."),
        ("The download limit is the same one as the toolbar's Speed Limiter, and covers torrents too.", "محدودیت دانلود همان محدودکنندهٔ سرعت نوار ابزار است و تورنت‌ها را هم شامل می‌شود."),
        ("Upload slots per torrent", "تعداد اسلات آپلود برای هر تورنت"),
        ("Maximum peers per torrent", "حداکثر همتا برای هر تورنت"),
        ("Keep sharing a torrent after it finishes downloading", "پس از پایان دانلود، تورنت همچنان به اشتراک گذاشته شود"),
        ("Off by default: a finished torrent just stops. To share one anyway, open its details window and choose Resume - nothing uploads until you say so.", "به‌طور پیش‌فرض غیرفعال است: تورنت تمام‌شده فقط متوقف می‌شود. برای اشتراک‌گذاری، پنجرهٔ جزئیات آن را باز کرده و ادامه را بزنید — چیزی آپلود نمی‌شود مگر خودتان بخواهید."),
        ("Resume sharing already-finished torrents when Makan starts", "هنگام اجرای Makan، اشتراک‌گذاری تورنت‌های تمام‌شده از سر گرفته شود"),
        ("Stop sharing once this much has been uploaded (%), 0 = never stop on ratio", "پس از رسیدن آپلود به این مقدار (٪) اشتراک‌گذاری متوقف شود، ۰ = هرگز بر اساس نسبت متوقف نشود"),
        ("Downloading and seeding are different activities and often wanted at different times - each has its own hours here. A torrent outside its allowed hours simply pauses; it resumes by itself once the hours come back around. A time you paused by hand stays paused regardless.", "دانلود و اشتراک‌گذاری فعالیت‌های متفاوتی هستند و اغلب در زمان‌های متفاوتی مورد نیازند - هرکدام ساعت‌های جداگانهٔ خود را اینجا دارند. تورنتی که خارج از ساعت مجاز باشد فقط متوقف می‌شود و با رسیدن دوبارهٔ ساعت مجاز، خودش ادامه می‌یابد. تورنتی که خودتان متوقف کرده‌اید همچنان متوقف می‌ماند."),
        ("Only download during these hours:", "فقط در این ساعت‌ها دانلود شود:"),
        ("Only seed during these hours:", "فقط در این ساعت‌ها اشتراک‌گذاری شود:"),
        ("24-hour time, for example 08:00", "زمان بر پایهٔ ۲۴ ساعته، مثلاً ۰۸:۰۰"),
        ("24-hour time, for example 23:00", "زمان بر پایهٔ ۲۴ ساعته، مثلاً ۲۳:۰۰"),
        ("24-hour time, for example 07:00 (crossing midnight is fine)", "زمان بر پایهٔ ۲۴ ساعته، مثلاً ۰۷:۰۰ (رد شدن از نیمه‌شب مشکلی ندارد)"),
        ("Finished - not sharing", "تمام‌شده - در حال اشتراک‌گذاری نیست"),
        ("Finished · not sharing (open it and choose Resume to seed)", "تمام‌شده · در حال اشتراک‌گذاری نیست (برای اشتراک‌گذاری آن را باز کرده و ادامه را بزنید)"),

        // ---- torrent details window
        ("Torrent details", "جزئیات تورنت"),
        ("Files", "فایل‌ها"),
        ("Peers", "همتاها"),
        ("Trackers", "ردیاب‌ها"),
        ("Priority", "اولویت"),
        ("Skip", "رد شود"),
        ("Normal", "عادی"),
        ("High", "بالا"),
        ("Down", "دانلود"),
        ("Up", "آپلود"),
        ("seeds", "سیدر"),
        ("known", "شناخته‌شده"),
        ("Ratio", "نسبت اشتراک"),
        ("ETA", "زمان باقی‌مانده"),
        ("Getting torrent info…", "دریافت اطلاعات تورنت…"),
        ("Checking files", "بررسی فایل‌ها"),
        ("Seeding", "اشتراک‌گذاری"),
        ("Paused", "متوقف‌شده"),
        ("Paused - not connected", "متوقف‌شده - متصل نیست"),
        ("Copy magnet link", "کپی لینک مگنت"),
        ("Remove…", "حذف…"),
        ("Remove torrent", "حذف تورنت"),
        ("Also delete the downloaded files from disk?", "فایل‌های دانلودشده از روی دیسک هم حذف شوند؟"),
        ("Download limit:", "محدودیت دانلود:"),
        ("Upload limit:", "محدودیت آپلود:"),
        ("Maximum download speed:", "حداکثر سرعت دانلود:"),
        ("KBytes/sec", "کیلوبایت بر ثانیه"),
        ("Remember Speed Limiter settings for this file on download stop/resume", "تنظیمات محدودکنندهٔ سرعت برای این فایل هنگام توقف/ادامهٔ دانلود به خاطر سپرده شود"),
        ("Options on completion", "گزینه‌ها پس از پایان"),
        ("Save To:", "ذخیره در:"),
        ("Show download complete dialog", "نمایش پنجرهٔ پایان دانلود"),
        ("These settings are unavailable when 'Show download complete dialog' is turned on", "وقتی «نمایش پنجرهٔ پایان دانلود» روشن است، این گزینه‌ها در دسترس نیستند"),
        ("Exit Makan when done", "خروج از ماکان پس از پایان"),
        ("Turn off computer when done", "خاموش کردن رایانه پس از پایان"),
        ("Force processes to terminate", "بستن اجباری برنامه‌ها"),
        ("<< Hide details", "<< پنهان کردن جزئیات"),
        ("Show details >>", "نمایش جزئیات >>"),
        ("Pause", "توقف"),
        ("Start", "شروع"),
        ("Start positions and download progress by connections", "نقطهٔ شروع و پیشرفت دانلود در هر اتصال"),
        ("Info", "توضیح"),
        ("Light", "روشن"),
        ("Dark", "تیره"),
        ("Orange", "نارنجی"),
        ("Epsilon", "اپسیلون"),
        ("Force Download", "دانلود اجباری"),
        ("Ignore the download/seed schedule for this torrent and keep it running", "زمان‌بندی دانلود/سیدینگ برای این تورنت نادیده گرفته شود و همچنان در حال اجرا بماند"),
        ("Stop this queue", "توقف این صف"),
        ("Start this queue", "شروع این صف"),
        ("Torrents", "تورنت‌ها"),
        ("Empty = torrents save to the main download folder above, same as everything else. A separate folder here applies to new torrents only (magnet links, .torrent files, from the browser or the phone remote page); torrents already added keep their current folder.", "خالی = تورنت‌ها در همان پوشهٔ دانلود اصلی بالا ذخیره می‌شوند، مثل بقیهٔ چیزها. یک پوشهٔ جداگانه در اینجا فقط روی تورنت‌های جدید اثر می‌گذارد (لینک مگنت، فایل تورنت، از مرورگر یا صفحهٔ ریموت گوشی)؛ تورنت‌های قبلاً اضافه‌شده در پوشهٔ فعلی خود می‌مانند."),
        ("Dark (blue grey)", "تاریک (آبی‌خاکستری)"),
        ("Follow Windows", "مطابق ویندوز"),
        ("The theme changes as soon as you press OK.", "پوسته به محض زدن «تأیید» تغییر می‌کند."),
        ("Show the download progress window when a download starts", "نمایش پنجرهٔ پیشرفت هنگام شروع دانلود"),
        ("YouTube & other sites", "یوتیوب و سایت‌های دیگر"),
        ("YouTube and many other video sites protect their videos. Makan reads them with the free program yt-dlp, runs the sites' player code with Deno, and joins video and sound with FFmpeg.", "یوتیوب و بسیاری از سایت‌های ویدیو از ویدیوهایشان محافظت می‌کنند. ماکان آن‌ها را با برنامهٔ رایگان yt-dlp می‌خواند، کد پخش‌کنندهٔ سایت‌ها را با Deno اجرا می‌کند و تصویر و صدا را با FFmpeg به هم می‌چسباند."),
        ("yt-dlp", "yt-dlp"),
        ("Deno", "Deno"),
        ("FFmpeg", "FFmpeg"),
        ("Also download FFmpeg (large, needed for videos above 360p and for MP3)", "FFmpeg هم دانلود شود (حجیم است؛ برای ویدیوهای بالاتر از ۳۶۰ و برای MP3 لازم است)"),
        ("Download / update tools", "دانلود / به‌روزرسانی ابزارها"),
        ("The tools are stored in Makan's own folder. yt-dlp keeps itself up to date, because YouTube changes often.", "ابزارها در پوشهٔ اختصاصی ماکان ذخیره می‌شوند. yt-dlp خودش را به‌روز نگه می‌دارد، چون یوتیوب مرتب تغییر می‌کند."),
        ("Path of yt-dlp (leave empty to use Makan's copy)", "مسیر yt-dlp (برای استفاده از نسخهٔ خود ماکان خالی بگذارید)"),
        ("Use the login of my browser (for private or age-restricted videos)", "استفاده از ورود (لاگین) مرورگر من (برای ویدیوهای خصوصی یا دارای محدودیت سنی)"),
        ("None", "هیچ"),
        ("Chrome", "Chrome"),
        ("Edge", "Edge"),
        ("Firefox", "Firefox"),
        ("Brave", "Brave"),
        ("Only download videos you have the right to save. Some sites forbid downloading in their terms of use.", "فقط ویدیوهایی را دانلود کنید که حق ذخیره‌کردنشان را دارید. برخی سایت‌ها دانلود را در شرایط استفادهٔ خود ممنوع کرده‌اند."),
        ("Receiving data...", "در حال دریافت اطلاعات..."),
        ("1 connection", "۱ اتصال"),
        ("{0} connections", "{0} اتصال"),
        ("connecting", "در حال اتصال"),
        ("idle", "بیکار"),
        ("done", "تمام"),
        ("Minimize", "کوچک کردن"),
        ("Hide options", "پنهان کردن تنظیمات"),
        ("On completion", "پس از پایان"),
        ("Nothing", "هیچ"),
        ("Show dialog", "نمایش پنجره"),
        ("Exit Epsilon when done", "خروج از اپسیلون پس از پایان"),
        ("Connecting...", "در حال اتصال..."),
        ("Waiting for a free download slot", "در انتظار یک جای خالی برای دانلود"),
        ("Yes", "بله"),
        ("No", "خیر"),
        ("unknown", "نامشخص"),
        ("Send GET...", "ارسال درخواست GET..."),
        ("Disconnect.", "قطع اتصال."),
        ("Download complete.", "دانلود کامل شد."),
        ("Merging…", "در حال ادغام…"),
        ("Reading video information…", "در حال خواندن اطلاعات ویدیو…"),
        ("YouTube needs yt-dlp. Open Options > YouTube & other sites and click \"Download / update tools\".", "یوتیوب به yt-dlp نیاز دارد. تنظیمات > یوتیوب و سایت‌های دیگر را باز کنید و روی «دانلود / به‌روزرسانی ابزارها» بزنید."),
        ("yt-dlp is not set up. Open Options > YouTube & other sites and click \"Download / update tools\".", "yt-dlp آماده نشده است. تنظیمات > یوتیوب و سایت‌های دیگر را باز کنید و روی «دانلود / به‌روزرسانی ابزارها» بزنید."),
        ("yt-dlp was not found. Open Options > YouTube & other sites and click \"Download / update tools\".", "yt-dlp پیدا نشد. تنظیمات > یوتیوب و سایت‌های دیگر را باز کنید و روی «دانلود / به‌روزرسانی ابزارها» بزنید."),
        ("yt-dlp took too long to read this page.", "yt-dlp برای خواندن این صفحه بیش از حد طول کشید."),
        ("This video can't be read: {0}", "خواندن این ویدیو ممکن نیست: {0}"),
        ("Nothing to download was found on this page.", "چیزی برای دانلود در این صفحه پیدا نشد."),
        ("MP4 video (with sound)", "ویدیوی MP4 (با صدا)"),
        ("Audio only", "فقط صدا"),
        ("Subtitle file (SRT)", "فایل زیرنویس (SRT)"),
        ("Audio only (M4A)", "فقط صدا (M4A)"),
        ("Audio only (MP3)", "فقط صدا (MP3)"),
        ("Subtitles: {0}", "زیرنویس: {0}"),
        ("Subtitles: {0} (auto-generated)", "زیرنویس: {0} (خودکار)"),
        ("not installed", "نصب نشده"),
        ("ready", "آماده"),
        ("Choose yt-dlp", "انتخاب yt-dlp"),
        ("All tools are ready.", "همهٔ ابزارها آماده‌اند."),
        ("The tools could not be installed:\n{0}", "نصب ابزارها ناموفق بود:\n{0}"),
        ("Downloading {0}… {1}%", "در حال دانلود {0}… {1}٪"),
        ("Downloading {0}… {1} MB", "در حال دانلود {0}… {1} مگابایت"),
        ("yt-dlp is ready.", "yt-dlp آماده است."),
        ("Deno is ready.", "Deno آماده است."),
        ("FFmpeg is ready.", "FFmpeg آماده است."),
        ("The Options window", "پنجرهٔ تنظیمات"),
        ("Epsilon Download Manager — Intelligent Download Center", "اپسیلون دانلود منیجر — مرکز هوشمند دانلود"),
        ("Intelligent _Center", "_مرکز هوشمند"),
        ("Intelligent Center", "مرکز هوشمند"),
        ("Epsilon Download Manager — Intelligent Center", "اپسیلون دانلود منیجر — مرکز هوشمند"),
        ("EPSILON DOWNLOAD MANAGER", "اپسیلون دانلود منیجر"),
        ("Fast, intelligent and private downloading", "دانلود سریع، هوشمند و خصوصی"),
        ("CREATED BY MAKAN A.D.", "ساخته‌شده توسط Makan A.D."),
        ("makanlab.tech", "makanlab.tech"),
        ("Open makanlab.tech", "باز کردن makanlab.tech"),
        ("Makan Lab", "Makan Lab"),
        ("Open Makan Lab", "باز کردن Makan Lab"),
        ("Server learning, bandwidth profiles, health checks, backup and more", "یادگیری سرور، پروفایل پهنای باند، بررسی سلامت، پشتیبان‌گیری و بیشتر"),
        ("SMART ENGINE ON", "موتور هوشمند روشن"),
        ("SMART ENGINE OFF", "موتور هوشمند خاموش"),
        ("BROWSER CONNECTED", "مرورگر متصل است"),
        ("BROWSER NOT CONNECTED", "مرورگر متصل نیست"),
        ("Search downloads by name or URL", "جست‌وجوی دانلودها با نام یا نشانی"),
        ("Keep the computer awake while files are downloading", "هنگام دانلود فایل‌ها رایانه را روشن نگه دار"),
        ("Prevents automatic sleep while a transfer is active. The display may still turn off normally.", "هنگام انتقال فعال از خواب خودکار رایانه جلوگیری می‌کند. نمایشگر همچنان می‌تواند به‌طور عادی خاموش شود."),
        ("DOWNLOAD", "دانلود"),
        ("SIZE", "حجم"),
        ("STATUS", "وضعیت"),
        ("TIME LEFT", "زمان باقی‌مانده"),
        ("SPEED", "سرعت"),
        ("QUEUE", "صف"),
        ("STATUS & PROGRESS", "وضعیت و پیشرفت"),
        ("PEERS", "پیرها"),
        ("UP SPEED", "سرعت آپلود"),
        ("SEEDS (PEERS)", "سیدها (پیرها)"),
        ("LAST TRY", "آخرین تلاش"),
        ("DESCRIPTION", "توضیحات"),
        ("·  Created by Makan A.D.", "·  ساخته‌شده توسط Makan A.D."),
        ("INTELLIGENT CENTER", "مرکز هوشمند"),
        ("Server learning · bandwidth profiles · health · recovery · backup", "یادگیری سرور · پروفایل پهنای باند · سلامت · بازیابی · پشتیبان"),
        ("Refresh", "تازه‌سازی"),
        ("Overview", "نمای کلی"),
        ("Server Intelligence", "هوش سرور"),
        ("Bandwidth", "پهنای باند"),
        ("Health Center", "مرکز سلامت"),
        ("Statistics", "آمار"),
        ("Recovery", "بازیابی"),
        ("Planner", "برنامه‌ریز"),
        ("Basket", "سبد"),
        ("Security & Backup", "امنیت و پشتیبان"),
        ("Live numbers from your download list and the engine.", "اعداد زندهٔ فهرست دانلود و موتور."),
        ("ACTIVE", "فعال"),
        ("QUEUED", "در صف"),
        ("COMPLETED", "کامل‌شده"),
        ("DOWNLOADED", "دریافت‌شده"),
        ("FASTEST", "سریع‌ترین"),
        ("Transferring now", "در حال انتقال"),
        ("Waiting for a free slot", "منتظر جای خالی"),
        ("Finished downloads", "دانلودهای تمام‌شده"),
        ("All data received so far", "کل داده‌های دریافت‌شده تا اینجا"),
        ("Best transfer right now", "بهترین انتقال در همین لحظه"),
        ("Server learning", "یادگیری سرور"),
        ("Makan remembers which servers throttle you and starts them with fewer connections next time. Nothing leaves your computer.", "ماکان به یاد می‌آورد کدام سرورها شما را محدود می‌کنند و دفعهٔ بعد با اتصال کمتر شروع می‌کند. هیچ چیزی از رایانهٔ شما خارج نمی‌شود."),
        ("Bandwidth profiles", "پروفایل‌های پهنای باند"),
        ("Switch the global speed limit in one click, for example while gaming or during a call.", "محدودیت سرعت کلی را با یک کلیک تغییر دهید، مثلاً هنگام بازی یا تماس."),
        ("Health and recovery", "سلامت و بازیابی"),
        ("Checks the database, disk space, browser link and tools, and lists downloads that were interrupted.", "پایگاه داده، فضای دیسک، اتصال مرورگر و ابزارها را بررسی می‌کند و دانلودهای نیمه‌تمام را فهرست می‌کند."),
        ("Private by design", "خصوصی از پایه"),
        ("Browser cookies are stored encrypted for your Windows account; diagnostic reports hide cookies and tokens.", "کوکی‌های مرورگر برای حساب ویندوز شما رمزگذاری‌شده ذخیره می‌شوند؛ گزارش‌های عیب‌یابی کوکی و توکن را پنهان می‌کنند."),
        ("Export diagnostic report", "خروجی گزارش عیب‌یابی"),
        ("Worked out from the current download list; no account and no upload.", "از فهرست فعلی دانلودها محاسبه می‌شود؛ بدون حساب کاربری و بدون ارسال."),
        ("TOTAL", "کل"),
        ("FAILED", "ناموفق"),
        ("STOPPED", "متوقف"),
        ("RETRIES", "تلاش مجدد"),
        ("AVERAGE SPEED", "سرعت میانگین"),
        ("FINISHED DATA", "حجم تمام‌شده"),
        ("Downloads in the list", "دانلودهای فهرست"),
        ("Need attention", "نیازمند توجه"),
        ("Waiting to be resumed", "منتظر ادامه"),
        ("Automatic retries so far", "تلاش‌های مجدد خودکار تا اینجا"),
        ("Of the running downloads", "از دانلودهای در حال اجرا"),
        ("Size of completed downloads", "حجم دانلودهای کامل"),
        ("By category", "بر اساس دسته"),
        ("No downloads yet.", "هنوز دانلودی نیست."),
        ("Smart download planner", "برنامه‌ریز هوشمند دانلود"),
        ("Paste an address to preview where Makan would save it and how many connections it would use. Nothing is downloaded.", "نشانی را بچسبانید تا ببینید ماکان آن را کجا ذخیره و با چند اتصال دانلود می‌کند. چیزی دانلود نمی‌شود."),
        ("Analyze address", "تحلیل نشانی"),
        ("Download basket", "سبد دانلود"),
        ("Collect addresses now and download them together later. The basket is kept between runs.", "نشانی‌ها را الان جمع کنید و بعداً یک‌جا دانلود کنید. سبد بین اجراها حفظ می‌شود."),
        ("Download all", "دانلود همه"),
        ("Export…", "خروجی…"),
        ("Clear", "پاک کردن"),
        ("Security and backup", "امنیت و پشتیبان"),
        ("Your download list lives in a local SQLite database. Makan keeps a backup copy that is refreshed every time it starts.", "فهرست دانلودها در یک پایگاه دادهٔ SQLite محلی است. ماکان یک نسخهٔ پشتیبان نگه می‌دارد که با هر شروع تازه می‌شود."),
        ("Check database", "بررسی پایگاه داده"),
        ("Create backup…", "ساخت پشتیبان…"),
        ("Open data folder", "باز کردن پوشهٔ داده"),
        ("If the database is ever damaged, Makan restores its automatic backup copy by itself the next time it starts.", "اگر پایگاه داده آسیب ببیند، ماکان در شروع بعدی خودش نسخهٔ پشتیبان خودکار را بازیابی می‌کند."),
        ("Server intelligence", "هوش سرور"),
        ("What Makan has learned from your finished downloads. A server that keeps refusing connections gets a lower limit.", "آنچه ماکان از دانلودهای تمام‌شدهٔ شما یاد گرفته است. سروری که مدام اتصال را رد می‌کند محدودیت کمتری می‌گیرد."),
        ("Nothing learned yet", "هنوز چیزی یاد گرفته نشده"),
        ("Finish a few downloads and Makan builds a history for each server.", "چند دانلود را کامل کنید تا ماکان برای هر سرور تاریخچه بسازد."),
        ("no connection limit learned", "محدودیتی برای اتصال یاد گرفته نشده"),
        ("up to {0} connections", "تا {0} اتصال"),
        ("downloads measured", "دانلود اندازه‌گیری‌شده"),
        ("throttling events", "بار محدودسازی"),
        ("Set the global speed limit in one click. It applies to all downloads at once; a limit on one download still wins.", "محدودیت سرعت کلی را با یک کلیک تنظیم کنید. برای همهٔ دانلودها اعمال می‌شود؛ محدودیت یک دانلود همچنان اولویت دارد."),
        ("Current global limit: unlimited", "محدودیت کلی فعلی: نامحدود"),
        ("Current global limit: {0} KB/s", "محدودیت کلی فعلی: {0} کیلوبایت بر ثانیه"),
        ("Unlimited", "نامحدود"),
        ("Active", "فعال"),
        ("Apply profile", "اعمال پروفایل"),
        ("Quick checks of the database, disk, network, browser link and optional tools.", "بررسی سریع پایگاه داده، دیسک، شبکه، اتصال مرورگر و ابزارهای اختیاری."),
        ("READY", "آماده"),
        ("OPTIONAL", "اختیاری"),
        ("CHECK", "بررسی"),
        ("Crash recovery", "بازیابی پس از خرابی"),
        ("Unfinished downloads that Makan found state files for. They continue from the saved position when you resume them.", "دانلودهای نیمه‌تمامی که ماکان فایل وضعیت آن‌ها را پیدا کرده است. با ادامه دادن، از موقعیت ذخیره‌شده ادامه می‌یابند."),
        ("Nothing waiting for recovery", "چیزی برای بازیابی نیست"),
        ("No interrupted download was found.", "دانلود نیمه‌تمامی پیدا نشد."),
        ("Database", "پایگاه داده"),
        ("Automatic backup copy", "نسخهٔ پشتیبان خودکار"),
        ("Portable mode", "حالت قابل‌حمل"),
        ("on", "روشن"),
        ("off", "خاموش"),
        ("Network", "شبکه"),
        ("offline", "آفلاین"),
        ("Fastest link", "سریع‌ترین اتصال"),
        ("Browser cookies are stored encrypted for your Windows account. Redirects never share cookies between sites. Diagnostic reports hide cookies and tokens.", "کوکی‌های مرورگر برای حساب ویندوز شما رمزگذاری‌شده ذخیره می‌شوند. تغییر مسیرها هرگز کوکی را بین سایت‌ها به اشتراک نمی‌گذارند. گزارش‌های عیب‌یابی کوکی و توکن را پنهان می‌کنند."),
        ("Enter a full http:// or https:// address.", "نشانی کامل http:// یا https:// را وارد کنید."),
        ("File name", "نام فایل"),
        ("Folder", "پوشه"),
        ("lowered: this server has throttled before", "کم‌شده: این سرور قبلاً محدود کرده است"),
        ("Enter a full http:// or https:// address that is not in the basket yet.", "نشانی کامل http:// یا https:// را وارد کنید که هنوز در سبد نیست."),
        ("Could not add {0}:\n{1}", "افزودن {0} ممکن نشد:\n{1}"),
        ("{0} YouTube link(s) stay in the basket: add them from the main window to choose a quality.", "{0} پیوند یوتیوب در سبد می‌ماند: برای انتخاب کیفیت آن‌ها را از پنجرهٔ اصلی اضافه کنید."),
        ("The database passed SQLite's integrity check.", "پایگاه داده آزمون سلامت SQLite را با موفقیت گذراند."),
        ("SQLite reports a problem in the database. Create a backup now and restart Makan.", "SQLite مشکلی در پایگاه داده گزارش می‌کند. همین حالا پشتیبان بگیرید و ماکان را دوباره راه‌اندازی کنید."),
        ("The backup was created.", "پشتیبان ساخته شد."),
        ("The backup failed:\n{0}", "ساخت پشتیبان ناموفق بود:\n{0}"),
        ("The diagnostic report was saved to:\n\n{0}", "گزارش عیب‌یابی ذخیره شد در:\n\n{0}"),
        ("The diagnostic report could not be created:\n{0}", "ساخت گزارش عیب‌یابی ممکن نشد:\n{0}"),
        ("Diagnostic report", "گزارش عیب‌یابی"),
        ("Smart connections: use fewer connections for servers that throttle me", "اتصال هوشمند: برای سرورهایی که مرا محدود می‌کنند اتصال کمتر استفاده شود"),
        ("Makan always starts with the number above. Only a server that answers 'too many requests' gets fewer connections next time (see the Intelligent Center).", "ماکان همیشه با عدد بالا شروع می‌کند. فقط سروری که «درخواست‌های بیش از حد» پاسخ می‌دهد دفعهٔ بعد اتصال کمتر می‌گیرد (مرکز هوشمند را ببینید).")
    };
}
